 GRANT SELECT ON "CUST_ADMIN"."V_CUSTOMER_FULFILLMENT2" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."EMAIL_VERIFY" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."COUPON_LOOKUP_CODES" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."CUSTOMER_SIGNUP" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."PERSON_EXT_KEY" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."PERSON_EXT_KEY_HISTORY" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."PREFERENCE_DETAIL" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."PREFERENCE_DETAIL_HISTORY" TO "CUST_READ";
 GRANT SELECT ON "CUST_ADMIN"."PREFERENCE_HEADER_HISTORY" TO "CUST_READ";
  GRANT SELECT ON "CUST_ADMIN"."QAS_DATA" TO "CUST_READ";
   GRANT SELECT ON "CUST_ADMIN"."TMP_ATG_ITEM_MAPPING" TO "CUST_READ";
GRANT SELECT ON "CUST_ADMIN"."TMP_ATG_LIST_MAPPING" TO "CUST_READ";
GRANT SELECT ON "CUST_ADMIN"."TMP_LOG" TO "CUST_READ";
GRANT SELECT ON "CUST_ADMIN"."ENTITLEMENT_CHANGE_REQUEST" TO "CUST_READ";
 